[versions]
# libraries
junit = "6.0.2"
assertj = "3.27.7"

# plugins
kotlin = "2.3.0"
pluginPublish = "2.0.0"

[libraries]
jupiterPlatform = { group = "org.junit.platform", name = "junit-platform-launcher" }
jupiterMain = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }

[bundles]
test = [
    "jupiterPlatform",
    "jupiterMain",
    "jupiterParams",
    "assertj",
]
