[versions]
# libraries
junit = "5.11.0"
assertj = "3.27.6"

# plugins
kotlin = "2.2.21"
pluginPublish = "1.3.1"

[libraries]
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
